description: CMFContentPanels is a plone portlets product to build composite pages.
  You can create new content which is composed of other contents as configurable 'content
  panels'.  You can change the layout, the panel skin and the content viewlet through
  the web.
exclude: [img, cp-layout-en.png, index.rst]
order: []
title: CMFContentPanels
