description: 投票和计数器：ATRatings为基于Archetypes的产品提供投票的功能，ATRatings底层接口由Geoff Davis创建，润普公司对该产品进行维护并完成了产品的使用界面。
exclude: [img, rating-zh.png, index.rst]
order: []
theme: default.html
theme_default: default.html
title: 'ATRatings: 投票和计数器引擎'
